#!/bin/bash

xset r rate 280 80 & # set the autorepeat
xset +dpms & # enable dpms
xset b off & # turn off bell

# touchpad and trackpoint settings
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
xinput set-button-map "TPPS/2 IBM TrackPoint" 1 0 3 &
xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Speed" 0.000001 &
xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Profile Enabled" 0, 0, 1 &
xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Natural Scrolling Enabled" 1 &
xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Custom Scroll Step" 0.000001 &
xinput --set-prop "TPPS/2 IBM TrackPoint" "libinput Accel Custom Motion Step" 0.000001 &

# move escape to it's correct location
setxkbmap -option caps:swapescape &

xrdb -merge "$HOME/.Xresources" -I"$HOME/.Xresources.d"

execute_cmd() {
    local cmd
    local MAX_ATTEMPTS
    local WAIT_DURATION
    local total_attempts

    cmd="$1"
    MAX_ATTEMPTS=5
    WAIT_DURATION="2s"

    # kill the process if exists
    
    if [ "$(pgrep "$cmd")" ];then
        killall "$cmd"
    fi

    total_attempts=0
    while [ "$(pgrep "$cmd")" ] && [ $total_attempts -lt $MAX_ATTEMPTS ] ; do
        sleep $WAIT_DURATION
        killall "$cmd"
        total_attempts=$((total_attempts+1))
    done

    # execute the process
    
    $cmd & 

    total_attempts=0
    while [ ! "$(pgrep "$cmd")" ] && [ $total_attempts -lt $MAX_ATTEMPTS ] ; do
        sleep $WAIT_DURATION
        $cmd &
        total_attempts=$((total_attempts+1))
    done
}

execute_cmd "volumeicon" &
execute_cmd "nm-applet" &
